services:
  - type: web
    name: my-flask-app
    env: python
    plan: free
    buildCommand: "pip install --upgrade pip && pip install -r requirements-web.txt"
    startCommand: "gunicorn app:app"
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
